import {FormEvent,useEffect,useState} from "react";
import {Navigate} from "react-router-dom";
import {useAuth} from "../context/AuthContext";
import {getMyQuota,getMyRequests,submitQuotaRequest,type QuotaRequest,type UserQuota} from "../services/userQuotaService";
export function MySpeechUsagePage(){const{isAuthenticated,user}=useAuth();const[quota,setQuota]=useState<UserQuota|null>(null);const[requests,setRequests]=useState<QuotaRequest[]>([]);const[service,setService]=useState("both");const[tts,setTts]=useState(1000);const[stt,setStt]=useState(60);const[reason,setReason]=useState("");const[msg,setMsg]=useState("");
useEffect(()=>{if(isAuthenticated&&user?.role!=="admin")Promise.all([getMyQuota(),getMyRequests()]).then(([q,r])=>{setQuota(q);setRequests(r)}).catch(()=>setMsg("Speech usage could not be loaded."))},[isAuthenticated,user]);if(!isAuthenticated)return <Navigate to="/login" replace/>;if(user?.role==="admin")return <Navigate to="/admin/user-quotas" replace/>;
const submit=async(e:FormEvent)=>{e.preventDefault();setMsg("");try{await submitQuotaRequest({service_type:service,requested_tts_characters:service!=="stt"?tts:undefined,requested_stt_seconds:service!=="tts"?stt:undefined,reason});setRequests(await getMyRequests());setQuota(await getMyQuota());setReason("");setMsg("Your request was submitted.")}catch(e){setMsg(e instanceof Error?e.message:"Request failed.")}};
return <section><p className="text-sm font-bold uppercase text-teal-700">Personal allowance</p><h1 className="mt-1 text-3xl font-bold">My Speech Usage</h1><p className="mt-2 text-slate-600">Review your current allowance and request additional access when needed.</p>{msg&&<p className="mt-5 rounded-lg border border-slate-200 bg-white p-4 font-semibold">{msg}</p>}{quota&&<><div className="mt-7 grid gap-5 lg:grid-cols-2"><Usage title="TTS characters" used={quota.tts_used} limit={quota.tts_limit+quota.tts_extra} remaining={quota.tts_remaining}/><Usage title="STT speech time" used={quota.stt_used} limit={quota.stt_limit+quota.stt_extra} remaining={quota.stt_remaining} seconds/></div><p className="mt-4 text-sm font-semibold text-slate-500">Current period: {quota.period_type} · Next reset: {quota.reset_date??"-"} · Status: <span className="capitalize">{quota.status}</span></p></>}
<div className="mt-8 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><form onSubmit={submit} className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Request additional quota</h2><label className="mt-4 block text-sm font-bold">Service<select value={service} onChange={e=>setService(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border px-3"><option value="both">TTS and STT</option><option value="tts">TTS</option><option value="stt">STT</option></select></label>{service!=="stt"&&<Field label="TTS characters" value={tts} set={setTts}/>} {service!=="tts"&&<Field label="STT seconds" value={stt} set={setStt}/>}<label className="mt-3 block text-sm font-bold">Reason<textarea required minLength={10} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border p-3"/></label><button disabled={Boolean(quota?.pending_request)} className="mt-4 min-h-11 rounded-lg bg-slate-900 px-5 font-bold text-white disabled:opacity-40">Submit request</button></form><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Request history</h2><div className="mt-3 space-y-3">{requests.length?requests.map(r=><article key={r.id} className="border-b py-3 last:border-0"><div className="flex justify-between"><strong className="uppercase">{r.service_type}</strong><span className="capitalize font-bold text-teal-700">{r.status.replace("_"," ")}</span></div><p className="mt-1 text-sm text-slate-600">{r.reason}</p>{r.admin_response&&<p className="mt-2 text-sm font-semibold">Admin: {r.admin_response}</p>}</article>):<p className="py-8 text-center text-slate-500">No requests yet.</p>}</div></section></div></section>}
function Usage({title,used,limit,remaining,seconds=false}:{title:string;used:number;limit:number;remaining:number;seconds?:boolean}){const pct=limit?Math.min(100,Math.round(used/limit*100)):100;const fmt=(n:number)=>seconds?`${Math.floor(n/60)}m ${n%60}s`:n.toLocaleString();return <article className="rounded-lg border border-slate-200 bg-white p-5"><div className="flex justify-between"><h2 className="text-lg font-bold">{title}</h2><strong>{pct}%</strong></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full ${pct>=95?"bg-rose-600":pct>=80?"bg-amber-500":"bg-teal-500"}`} style={{width:`${pct}%`}}/></div><div className="mt-4 grid grid-cols-3 gap-3 text-sm"><span>Used<br/><strong>{fmt(used)}</strong></span><span>Remaining<br/><strong>{fmt(remaining)}</strong></span><span>Limit<br/><strong>{fmt(limit)}</strong></span></div></article>}
function Field({label,value,set}:{label:string;value:number;set:(n:number)=>void}){return <label className="mt-3 block text-sm font-bold">{label}<input type="number" min={1} required value={value} onChange={e=>set(Number(e.target.value))} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label>}
