import type { LanguageCode } from "../i18n";

type ComputerVisionText = {
  title: string; description: string; samples: string; scenario: string; attempt: string;
  open: string; back: string; timestamp: string; yaw: string; pitch: string; roll: string;
  eyeDirection: string; interaction: string; yes: string; no: string; previous: string;
  next: string; missing: string; left: string; center: string; right: string;
};

// Same six languages and keyed translation structure as the existing admin pages.
export const adminComputerVisionTranslations: Record<LanguageCode, ComputerVisionText> = {
  en: { title: "Computer vision recordings", description: "Inspect saved analysis data. Amber rows indicate keyboard or mouse activity.", samples: "Samples", scenario: "Scenario", attempt: "Scenario attempt", open: "View samples", back: "Back to recordings", timestamp: "Elapsed time (ms)", yaw: "Yaw (°)", pitch: "Pitch (°)", roll: "Roll (°)", eyeDirection: "Estimated eye direction", interaction: "User interacting", yes: "Yes", no: "No", previous: "Previous", next: "Next", missing: "Unavailable", left: "Left", center: "Center", right: "Right" },
  es: { title: "Registros de visión por computadora", description: "Consulta los datos de análisis guardados. Las filas ámbar indican actividad del teclado o ratón.", samples: "Muestras", scenario: "Escenario", attempt: "Intento del escenario", open: "Ver muestras", back: "Volver a los registros", timestamp: "Tiempo transcurrido (ms)", yaw: "Giro horizontal (°)", pitch: "Giro vertical (°)", roll: "Inclinación lateral (°)", eyeDirection: "Dirección estimada de los ojos", interaction: "Usuario interactuando", yes: "Sí", no: "No", previous: "Anterior", next: "Siguiente", missing: "No disponible", left: "Izquierda", center: "Centro", right: "Derecha" },
  de: { title: "Computer-Vision-Aufzeichnungen", description: "Gespeicherte Analysedaten ansehen. Gelbe Zeilen zeigen Tastatur- oder Mausaktivität an.", samples: "Messwerte", scenario: "Szenario", attempt: "Szenarioversuch", open: "Messwerte ansehen", back: "Zurück zu den Aufzeichnungen", timestamp: "Vergangene Zeit (ms)", yaw: "Drehung links/rechts (°)", pitch: "Drehung oben/unten (°)", roll: "Seitliche Neigung (°)", eyeDirection: "Geschätzte Augenrichtung", interaction: "Nutzer interagiert", yes: "Ja", no: "Nein", previous: "Zurück", next: "Weiter", missing: "Nicht verfügbar", left: "Links", center: "Mitte", right: "Rechts" },
  tr: { title: "Bilgisayarlı görü kayıtları", description: "Kaydedilen analiz verilerini inceleyin. Sarı satırlar klavye veya fare etkinliğini gösterir.", samples: "Örnekler", scenario: "Senaryo", attempt: "Senaryo denemesi", open: "Örnekleri görüntüle", back: "Kayıtlara dön", timestamp: "Geçen süre (ms)", yaw: "Sağa/sola dönüş (°)", pitch: "Yukarı/aşağı dönüş (°)", roll: "Yana eğilme (°)", eyeDirection: "Tahmini göz yönü", interaction: "Kullanıcı etkileşimde", yes: "Evet", no: "Hayır", previous: "Önceki", next: "Sonraki", missing: "Kullanılamıyor", left: "Sol", center: "Orta", right: "Sağ" },
  pt: { title: "Registros de visão computacional", description: "Inspecione os dados de análise salvos. As linhas amarelas indicam atividade do teclado ou mouse.", samples: "Amostras", scenario: "Cenário", attempt: "Tentativa do cenário", open: "Ver amostras", back: "Voltar aos registros", timestamp: "Tempo decorrido (ms)", yaw: "Rotação horizontal (°)", pitch: "Rotação vertical (°)", roll: "Inclinação lateral (°)", eyeDirection: "Direção estimada dos olhos", interaction: "Usuário interagindo", yes: "Sim", no: "Não", previous: "Anterior", next: "Próxima", missing: "Indisponível", left: "Esquerda", center: "Centro", right: "Direita" },
  fr: { title: "Enregistrements de vision par ordinateur", description: "Consultez les données d’analyse enregistrées. Les lignes jaunes indiquent une activité du clavier ou de la souris.", samples: "Échantillons", scenario: "Scénario", attempt: "Tentative du scénario", open: "Voir les échantillons", back: "Retour aux enregistrements", timestamp: "Temps écoulé (ms)", yaw: "Rotation gauche/droite (°)", pitch: "Rotation haut/bas (°)", roll: "Inclinaison latérale (°)", eyeDirection: "Direction estimée des yeux", interaction: "Utilisateur en interaction", yes: "Oui", no: "Non", previous: "Précédente", next: "Suivante", missing: "Indisponible", left: "Gauche", center: "Centre", right: "Droite" },
};
