import type { LanguageCode } from "../i18n";

type ComputerVisionText = {
  title: string; description: string; samples: string; scenario: string; attempt: string;
  open: string; back: string; timestamp: string; yaw: string; pitch: string; roll: string;
  eyeDirection: string; interaction: string; yes: string; no: string; previous: string;
  next: string; missing: string; left: string; center: string; right: string;
  selectorDescription: string; viewRecordings: string; available: string; comingSoon: string;
  date: string; hour: string; minute: string; second: string; sessionId: string;
  showTrackingData: string; pagination: string;
};

// Same six languages and keyed translation structure as the existing admin pages.
export const adminComputerVisionTranslations: Record<LanguageCode, ComputerVisionText> = {
  en: { title: "Computer vision recordings", description: "Review saved face and eye movement data.", samples: "Tracking data", scenario: "Scenario", attempt: "Scenario attempt ID", open: "View details", back: "Back to recordings", timestamp: "Session time", yaw: "Yaw (°)", pitch: "Pitch (°)", roll: "Roll (°)", eyeDirection: "Eye direction", interaction: "Keyboard/mouse activity", yes: "Yes", no: "No", previous: "Previous", next: "Next", missing: "Unavailable", left: "Left", center: "Center", right: "Right", selectorDescription: "Select a scenario to review its computer vision recordings.", viewRecordings: "View recordings", available: "Available", comingSoon: "Coming soon", date: "Date", hour: "hr", minute: "min", second: "sec", sessionId: "Session ID", showTrackingData: "Show tracking data", pagination: "Pages" },
  es: { title: "Registros de visión por computadora", description: "Consulta los datos guardados del movimiento del rostro y los ojos.", samples: "Datos de seguimiento", scenario: "Escenario", attempt: "ID del intento del escenario", open: "Ver detalles", back: "Volver a los registros", timestamp: "Tiempo de sesión", yaw: "Giro horizontal (°)", pitch: "Giro vertical (°)", roll: "Inclinación lateral (°)", eyeDirection: "Dirección de los ojos", interaction: "Actividad del teclado/ratón", yes: "Sí", no: "No", previous: "Anterior", next: "Siguiente", missing: "No disponible", left: "Izquierda", center: "Centro", right: "Derecha", selectorDescription: "Selecciona un escenario para consultar sus registros de visión por computadora.", viewRecordings: "Ver registros", available: "Disponible", comingSoon: "Próximamente", date: "Fecha", hour: "h", minute: "min", second: "s", sessionId: "ID de sesión", showTrackingData: "Mostrar datos de seguimiento", pagination: "Páginas" },
  de: { title: "Computer-Vision-Aufzeichnungen", description: "Gespeicherte Daten zu Gesichts- und Augenbewegungen ansehen.", samples: "Erfassungsdaten", scenario: "Szenario", attempt: "ID des Szenarioversuchs", open: "Details ansehen", back: "Zurück zu den Aufzeichnungen", timestamp: "Sitzungszeit", yaw: "Drehung links/rechts (°)", pitch: "Drehung oben/unten (°)", roll: "Seitliche Neigung (°)", eyeDirection: "Augenrichtung", interaction: "Tastatur-/Mausaktivität", yes: "Ja", no: "Nein", previous: "Zurück", next: "Weiter", missing: "Nicht verfügbar", left: "Links", center: "Mitte", right: "Rechts", selectorDescription: "Wähle ein Szenario, um die Computer-Vision-Aufzeichnungen anzusehen.", viewRecordings: "Aufzeichnungen ansehen", available: "Verfügbar", comingSoon: "Demnächst", date: "Datum", hour: "Std.", minute: "Min.", second: "Sek.", sessionId: "Sitzungs-ID", showTrackingData: "Erfassungsdaten anzeigen", pagination: "Seiten" },
  tr: { title: "Bilgisayarlı görü kayıtları", description: "Kaydedilen yüz ve göz hareketi verilerini inceleyin.", samples: "İzleme verileri", scenario: "Senaryo", attempt: "Senaryo deneme kimliği", open: "Ayrıntıları görüntüle", back: "Kayıtlara dön", timestamp: "Oturum süresi", yaw: "Sağa/sola dönüş (°)", pitch: "Yukarı/aşağı dönüş (°)", roll: "Yana eğilme (°)", eyeDirection: "Göz yönü", interaction: "Klavye/fare etkinliği", yes: "Evet", no: "Hayır", previous: "Önceki", next: "Sonraki", missing: "Kullanılamıyor", left: "Sol", center: "Orta", right: "Sağ", selectorDescription: "Bilgisayarlı görü kayıtlarını incelemek için bir senaryo seçin.", viewRecordings: "Kayıtları görüntüle", available: "Kullanılabilir", comingSoon: "Yakında", date: "Tarih", hour: "sa", minute: "dk", second: "sn", sessionId: "Oturum kimliği", showTrackingData: "İzleme verilerini göster", pagination: "Sayfalar" },
  pt: { title: "Registros de visão computacional", description: "Veja os dados salvos dos movimentos do rosto e dos olhos.", samples: "Dados de rastreamento", scenario: "Cenário", attempt: "ID da tentativa do cenário", open: "Ver detalhes", back: "Voltar aos registros", timestamp: "Tempo da sessão", yaw: "Rotação horizontal (°)", pitch: "Rotação vertical (°)", roll: "Inclinação lateral (°)", eyeDirection: "Direção dos olhos", interaction: "Atividade do teclado/mouse", yes: "Sim", no: "Não", previous: "Anterior", next: "Próxima", missing: "Indisponível", left: "Esquerda", center: "Centro", right: "Direita", selectorDescription: "Selecione um cenário para consultar seus registros de visão computacional.", viewRecordings: "Ver registros", available: "Disponível", comingSoon: "Em breve", date: "Data", hour: "h", minute: "min", second: "s", sessionId: "ID da sessão", showTrackingData: "Mostrar dados de rastreamento", pagination: "Páginas" },
  fr: { title: "Enregistrements de vision par ordinateur", description: "Consultez les données enregistrées des mouvements du visage et des yeux.", samples: "Données de suivi", scenario: "Scénario", attempt: "ID de la tentative du scénario", open: "Voir les détails", back: "Retour aux enregistrements", timestamp: "Temps de session", yaw: "Rotation gauche/droite (°)", pitch: "Rotation haut/bas (°)", roll: "Inclinaison latérale (°)", eyeDirection: "Direction des yeux", interaction: "Activité du clavier/de la souris", yes: "Oui", no: "Non", previous: "Précédente", next: "Suivante", missing: "Indisponible", left: "Gauche", center: "Centre", right: "Droite", selectorDescription: "Sélectionnez un scénario pour consulter ses enregistrements de vision par ordinateur.", viewRecordings: "Voir les enregistrements", available: "Disponible", comingSoon: "Bientôt disponible", date: "Date", hour: "h", minute: "min", second: "s", sessionId: "ID de session", showTrackingData: "Afficher les données de suivi", pagination: "Pages" },
};
