import type { LanguageCode } from "../i18n";

type PreviewText = { title: string; on: string; off: string; localOnly: string; consentRequired: string;
  unavailable: string; camera: string; face: string; landmarks: string };
export const adminFaceTrackingPreviewTranslations: Record<LanguageCode, PreviewText> = {
  en: { title: "Computer Vision Preview", on: "ON", off: "OFF", localOnly: "Local admin preview only. Angles and eye direction are approximate. No video or images are uploaded or saved.", consentRequired: "Preview requires Yes for analysis data recording in scenario setup.", unavailable: "Preview unavailable. The scenario can continue.", camera: "Camera active", face: "Face detected", landmarks: "Landmarks" },
  es: { title: "Vista previa de visión por computadora", on: "ACTIVADA", off: "DESACTIVADA", localOnly: "Vista local solo para administradores. Los ángulos y la dirección de los ojos son aproximados. No se suben ni guardan videos o imágenes.", consentRequired: "La vista previa requiere elegir Sí para guardar datos de análisis al configurar el escenario.", unavailable: "Vista previa no disponible. El escenario puede continuar.", camera: "Cámara activa", face: "Rostro detectado", landmarks: "Puntos faciales" },
  de: { title: "Computer-Vision-Vorschau", on: "AN", off: "AUS", localOnly: "Lokale Vorschau nur für Administratoren. Winkel und Augenrichtung sind ungefähre Werte. Videos und Bilder werden weder hochgeladen noch gespeichert.", consentRequired: "Für die Vorschau muss beim Szenariostart Ja zum Speichern der Analysedaten gewählt werden.", unavailable: "Vorschau nicht verfügbar. Das Szenario kann fortgesetzt werden.", camera: "Kamera aktiv", face: "Gesicht erkannt", landmarks: "Gesichtspunkte" },
  tr: { title: "Bilgisayarlı Görü Önizlemesi", on: "AÇIK", off: "KAPALI", localOnly: "Yalnızca yöneticiler için yerel önizleme. Açılar ve göz yönü yaklaşık değerlerdir. Video veya görüntü yüklenmez ya da kaydedilmez.", consentRequired: "Önizleme için senaryo ayarlarında analiz verilerinin kaydedilmesine Evet seçilmelidir.", unavailable: "Önizleme kullanılamıyor. Senaryo devam edebilir.", camera: "Kamera etkin", face: "Yüz algılandı", landmarks: "Yüz noktaları" },
  pt: { title: "Prévia de visão computacional", on: "LIGADA", off: "DESLIGADA", localOnly: "Prévia local apenas para administradores. Os ângulos e a direção dos olhos são aproximados. Nenhum vídeo ou imagem é enviado ou salvo.", consentRequired: "A prévia exige selecionar Sim para salvar os dados de análise na configuração do cenário.", unavailable: "Prévia indisponível. O cenário pode continuar.", camera: "Câmera ativa", face: "Rosto detectado", landmarks: "Pontos faciais" },
  fr: { title: "Aperçu de vision par ordinateur", on: "ACTIVÉ", off: "DÉSACTIVÉ", localOnly: "Aperçu local réservé aux administrateurs. Les angles et la direction des yeux sont approximatifs. Aucune vidéo ni image n’est envoyée ou enregistrée.", consentRequired: "L’aperçu nécessite de choisir Oui pour enregistrer les données d’analyse dans la configuration du scénario.", unavailable: "Aperçu indisponible. Le scénario peut continuer.", camera: "Caméra active", face: "Visage détecté", landmarks: "Points du visage" },
};
