import type { LanguageCode } from "../i18n";

export type BillAssistantStep = "login" | "bill-selection" | "bill-details" | "card-payment" | "payment-error" | "success" | "receipt";

type BillAssistantText = {
  panelTitle: string;
  guidedMode: string;
  soundOn: string;
  soundOff: string;
  turnSoundOn: string;
  turnSoundOff: string;
  repeat: string;
  stop: string;
  voiceError: string;
  safety: string;
  reviewBill: (bill: string) => string;
  messages: Record<BillAssistantStep, string>;
};

export const billAssistantTranslations: Record<LanguageCode, BillAssistantText> = {
  en: { panelTitle: "ASSIST-AI Assistant", guidedMode: "Guided bill payment", soundOn: "Sound on", soundOff: "Sound off", turnSoundOn: "Turn sound on", turnSoundOff: "Turn sound off", repeat: "Repeat assistant message", stop: "Stop voice", voiceError: "The assistant voice could not play. Please try again.", safety: "Use only the information shown in this scenario. Do not enter a real account or card.", reviewBill: (bill) => `Review your ${bill} bill, then select Pay by credit card when you are ready.`, messages: { login: "Log in using the username and password you created.", "bill-selection": "Choose one of the unpaid bills you would like to review and pay.", "bill-details": "Review the bill information. When you are ready, select Pay by credit card.", "card-payment": "Copy the information shown on the card into the matching fields. Select Show hints if you need help.", "payment-error": "The payment did not go through. Check the card information and try again.", success: "Thank you. Your bill has been paid successfully. You can view a receipt, pay another bill, or finish and leave.", receipt: "This is your electronic payment receipt. You can save it as a PDF, pay another bill, or finish and leave." } },
  es: { panelTitle: "Asistente ASSIST-AI", guidedMode: "Pago guiado de facturas", soundOn: "Sonido activado", soundOff: "Sonido desactivado", turnSoundOn: "Activar sonido", turnSoundOff: "Desactivar sonido", repeat: "Repetir mensaje", stop: "Detener voz", voiceError: "No se pudo reproducir la voz. Inténtalo de nuevo.", safety: "Usa solo la información mostrada en este escenario. No introduzcas una cuenta o tarjeta real.", reviewBill: (bill) => `Revisa tu factura de ${bill} y selecciona Pagar con tarjeta cuando estés listo.`, messages: { login: "Inicia sesión con el usuario y la contraseña que creaste.", "bill-selection": "Elige una de las facturas pendientes que deseas revisar y pagar.", "bill-details": "Revisa los datos de la factura. Cuando estés listo, selecciona Pagar con tarjeta.", "card-payment": "Copia los datos de la tarjeta en los campos correspondientes. Selecciona Mostrar pistas si necesitas ayuda.", "payment-error": "El pago no se ha procesado. Comprueba los datos de la tarjeta e inténtalo de nuevo.", success: "Gracias. Tu factura se ha pagado correctamente. Puedes ver el recibo, pagar otra factura o finalizar.", receipt: "Este es tu recibo electrónico. Puedes guardarlo como PDF, pagar otra factura o finalizar." } },
  de: { panelTitle: "ASSIST-AI Assistent", guidedMode: "Geführte Rechnungszahlung", soundOn: "Ton an", soundOff: "Ton aus", turnSoundOn: "Ton einschalten", turnSoundOff: "Ton ausschalten", repeat: "Nachricht wiederholen", stop: "Stimme stoppen", voiceError: "Die Stimme konnte nicht abgespielt werden. Versuchen Sie es erneut.", safety: "Verwenden Sie nur die in diesem Szenario gezeigten Daten. Geben Sie kein echtes Konto und keine echte Karte ein.", reviewBill: (bill) => `Prüfen Sie Ihre ${bill}-Rechnung und wählen Sie anschließend Mit Kreditkarte bezahlen.`, messages: { login: "Melden Sie sich mit dem erstellten Benutzernamen und Passwort an.", "bill-selection": "Wählen Sie eine unbezahlte Rechnung zum Prüfen und Bezahlen aus.", "bill-details": "Prüfen Sie die Rechnungsdaten. Wählen Sie anschließend Mit Kreditkarte bezahlen.", "card-payment": "Übertragen Sie die Kartendaten in die passenden Felder. Wählen Sie Hinweise anzeigen, wenn Sie Hilfe benötigen.", "payment-error": "Die Zahlung wurde nicht verarbeitet. Prüfen Sie die Kartendaten und versuchen Sie es erneut.", success: "Vielen Dank. Ihre Rechnung wurde bezahlt. Sie können den Beleg anzeigen, eine weitere Rechnung bezahlen oder die Seite verlassen.", receipt: "Dies ist Ihr elektronischer Zahlungsbeleg. Sie können ihn als PDF speichern, eine weitere Rechnung bezahlen oder die Seite verlassen." } },
  tr: { panelTitle: "ASSIST-AI Asistan", guidedMode: "Yönlendirmeli fatura ödeme", soundOn: "Ses açık", soundOff: "Ses kapalı", turnSoundOn: "Sesi aç", turnSoundOff: "Sesi kapat", repeat: "Asistan mesajını tekrarla", stop: "Sesi durdur", voiceError: "Asistan sesi oynatılamadı. Lütfen tekrar deneyin.", safety: "Yalnızca bu senaryoda gösterilen bilgileri kullanın. Gerçek hesap veya kart bilgisi girmeyin.", reviewBill: (bill) => `${bill} faturanızın bilgilerini inceleyin ve hazır olduğunuzda Kredi kartıyla öde seçeneğini seçin.`, messages: { login: "Oluşturduğunuz kullanıcı adı ve parola ile giriş yapın.", "bill-selection": "İncelemek ve ödemek istediğiniz ödenmemiş faturayı seçin.", "bill-details": "Fatura bilgilerini inceleyin. Hazır olduğunuzda Kredi kartıyla öde seçeneğini seçin.", "card-payment": "Kartta gösterilen bilgileri eşleşen alanlara yazın. Yardıma ihtiyacınız varsa İpuçlarını göster seçeneğini seçin.", "payment-error": "Ödeme tamamlanamadı. Kart bilgilerini kontrol edip tekrar deneyin.", success: "Teşekkürler. Faturanız başarıyla ödendi. Makbuzu görüntüleyebilir, başka bir fatura ödeyebilir veya işlemi bitirebilirsiniz.", receipt: "Bu elektronik ödeme makbuzunuzdur. PDF olarak kaydedebilir, başka bir fatura ödeyebilir veya işlemi bitirebilirsiniz." } },
  pt: { panelTitle: "Assistente ASSIST-AI", guidedMode: "Pagamento guiado de faturas", soundOn: "Som ligado", soundOff: "Som desligado", turnSoundOn: "Ligar som", turnSoundOff: "Desligar som", repeat: "Repetir mensagem", stop: "Parar voz", voiceError: "Não foi possível reproduzir a voz. Tente novamente.", safety: "Use apenas as informações apresentadas neste cenário. Não introduza uma conta ou cartão real.", reviewBill: (bill) => `Consulte os dados da sua fatura de ${bill} e selecione Pagar com cartão quando estiver pronto.`, messages: { login: "Inicie sessão com o utilizador e a palavra-passe que criou.", "bill-selection": "Escolha uma fatura por pagar para consultar e pagar.", "bill-details": "Consulte os dados da fatura. Quando estiver pronto, selecione Pagar com cartão.", "card-payment": "Copie os dados do cartão para os campos correspondentes. Se precisar de ajuda, selecione Mostrar dicas.", "payment-error": "O pagamento não foi processado. Verifique os dados do cartão e tente novamente.", success: "Obrigado. A sua fatura foi paga. Pode ver o recibo, pagar outra fatura ou terminar.", receipt: "Este é o seu recibo eletrónico. Pode guardá-lo como PDF, pagar outra fatura ou terminar." } },
  fr: { panelTitle: "Assistant ASSIST-AI", guidedMode: "Paiement guidé de factures", soundOn: "Son activé", soundOff: "Son désactivé", turnSoundOn: "Activer le son", turnSoundOff: "Désactiver le son", repeat: "Répéter le message", stop: "Arrêter la voix", voiceError: "La voix n’a pas pu être lue. Veuillez réessayer.", safety: "Utilisez uniquement les informations affichées dans ce scénario. Ne saisissez pas de vrai compte ni de vraie carte.", reviewBill: (bill) => `Vérifiez les informations de votre facture de ${bill}, puis sélectionnez Payer par carte lorsque vous êtes prêt.`, messages: { login: "Connectez-vous avec l’identifiant et le mot de passe que vous avez créés.", "bill-selection": "Choisissez une facture impayée à consulter et à payer.", "bill-details": "Vérifiez les informations de la facture. Lorsque vous êtes prêt, sélectionnez Payer par carte.", "card-payment": "Recopiez les informations de la carte dans les champs correspondants. Sélectionnez Afficher les indices si vous avez besoin d’aide.", "payment-error": "Le paiement n’a pas abouti. Vérifiez les informations de la carte et réessayez.", success: "Merci. Votre facture a été payée. Vous pouvez afficher le reçu, payer une autre facture ou terminer.", receipt: "Voici votre reçu électronique. Vous pouvez l’enregistrer au format PDF, payer une autre facture ou terminer." } },
};

export const billCardPaymentGuidance: Record<LanguageCode, string> = {
  en: "This is your credit card for paying the bill. Enter the information shown on the card to complete your payment.",
  es: "Esta es tu tarjeta de crédito para pagar la factura. Introduce la información que aparece en la tarjeta para completar el pago.",
  de: "Dies ist Ihre Kreditkarte zum Bezahlen der Rechnung. Geben Sie die auf der Karte angezeigten Daten ein, um die Zahlung abzuschließen.",
  tr: "Fatura ödemenizi tamamlamak için kredi kartında yer alan bilgileri ilgili alanlara girin.",
  pt: "Este é o seu cartão de crédito para pagar a fatura. Introduza os dados apresentados no cartão para concluir o pagamento.",
  fr: "Voici votre carte de crédit pour régler la facture. Saisissez les informations affichées sur la carte pour effectuer le paiement.",
};
