import type { LanguageCode } from "../i18n";

type SummaryText = {
  title: string; all: string; excluding: string; total: string; valid: string; missing: string;
  interacting: string; interactionPercentage: string; minimum: string; maximum: string;
  mean: string; standardDeviation: string; range: string; count: string; percentage: string;
  unknown: string; eyeChanges: string; definitions: string;
};
export const computerVisionSummaryTranslations: Record<LanguageCode, SummaryText> = {
  en: { title: "Session Summary", all: "All samples", excluding: "Excluding interaction samples", total: "Total samples", valid: "Valid head samples", missing: "Missing head samples", interacting: "Interaction samples", interactionPercentage: "Interaction percentage", minimum: "Minimum", maximum: "Maximum", mean: "Mean", standardDeviation: "Population standard deviation", range: "Range", count: "Count", percentage: "Percentage", unknown: "Unknown", eyeChanges: "Eye-direction changes", definitions: "Head metrics use samples with three available angles. Eye percentages include unknown samples. Eye changes count consecutive known directions; missing or excluded samples break the sequence. Percentages use the sample total in each group." },
  es: { title: "Resumen de la sesión", all: "Todas las muestras", excluding: "Sin muestras de interacción", total: "Total de muestras", valid: "Muestras válidas de la cabeza", missing: "Muestras de cabeza no disponibles", interacting: "Muestras de interacción", interactionPercentage: "Porcentaje de interacción", minimum: "Mínimo", maximum: "Máximo", mean: "Media", standardDeviation: "Desviación estándar poblacional", range: "Rango", count: "Cantidad", percentage: "Porcentaje", unknown: "Desconocida", eyeChanges: "Cambios de dirección de los ojos", definitions: "Las métricas de cabeza usan muestras con tres ángulos disponibles. Los porcentajes de ojos incluyen muestras desconocidas. Los cambios cuentan direcciones conocidas consecutivas; las muestras faltantes o excluidas interrumpen la secuencia. Los porcentajes usan el total de muestras de cada grupo." },
  de: { title: "Sitzungsübersicht", all: "Alle Messwerte", excluding: "Ohne Interaktionsmesswerte", total: "Messwerte insgesamt", valid: "Gültige Kopfmesswerte", missing: "Fehlende Kopfmesswerte", interacting: "Interaktionsmesswerte", interactionPercentage: "Interaktionsanteil", minimum: "Minimum", maximum: "Maximum", mean: "Mittelwert", standardDeviation: "Populationsstandardabweichung", range: "Spannweite", count: "Anzahl", percentage: "Prozent", unknown: "Unbekannt", eyeChanges: "Änderungen der Augenrichtung", definitions: "Kopfmetriken verwenden Messwerte mit drei verfügbaren Winkeln. Augenprozente enthalten unbekannte Werte. Änderungen zählen aufeinanderfolgende bekannte Richtungen; fehlende oder ausgeschlossene Messwerte unterbrechen die Folge. Prozente beziehen sich auf die Gesamtzahl je Gruppe." },
  tr: { title: "Oturum Özeti", all: "Tüm örnekler", excluding: "Etkileşim örnekleri hariç", total: "Toplam örnek", valid: "Geçerli baş örnekleri", missing: "Baş verisi eksik örnekler", interacting: "Etkileşim örnekleri", interactionPercentage: "Etkileşim yüzdesi", minimum: "Minimum", maximum: "Maksimum", mean: "Ortalama", standardDeviation: "Popülasyon standart sapması", range: "Aralık", count: "Sayı", percentage: "Yüzde", unknown: "Bilinmiyor", eyeChanges: "Göz yönü değişimleri", definitions: "Baş ölçümleri, üç açısı da mevcut olan örnekleri kullanır. Göz yüzdeleri bilinmeyen örnekleri de içerir. Değişimler ardışık bilinen yönler arasında sayılır; eksik veya hariç tutulan örnekler diziyi keser. Yüzdeler her grubun toplam örnek sayısına göre hesaplanır." },
  pt: { title: "Resumo da sessão", all: "Todas as amostras", excluding: "Sem amostras de interação", total: "Total de amostras", valid: "Amostras válidas da cabeça", missing: "Amostras sem dados da cabeça", interacting: "Amostras de interação", interactionPercentage: "Porcentagem de interação", minimum: "Mínimo", maximum: "Máximo", mean: "Média", standardDeviation: "Desvio padrão populacional", range: "Amplitude", count: "Contagem", percentage: "Porcentagem", unknown: "Desconhecida", eyeChanges: "Mudanças na direção dos olhos", definitions: "As métricas da cabeça usam amostras com três ângulos disponíveis. As porcentagens dos olhos incluem amostras desconhecidas. As mudanças contam direções conhecidas consecutivas; amostras ausentes ou excluídas interrompem a sequência. As porcentagens usam o total de amostras de cada grupo." },
  fr: { title: "Résumé de la session", all: "Tous les échantillons", excluding: "Sans les échantillons d’interaction", total: "Total des échantillons", valid: "Échantillons de tête valides", missing: "Échantillons sans données de tête", interacting: "Échantillons d’interaction", interactionPercentage: "Pourcentage d’interaction", minimum: "Minimum", maximum: "Maximum", mean: "Moyenne", standardDeviation: "Écart-type de population", range: "Étendue", count: "Nombre", percentage: "Pourcentage", unknown: "Inconnue", eyeChanges: "Changements de direction des yeux", definitions: "Les mesures de tête utilisent les échantillons avec trois angles disponibles. Les pourcentages des yeux incluent les valeurs inconnues. Les changements comptent les directions connues consécutives ; les échantillons manquants ou exclus interrompent la séquence. Les pourcentages utilisent le total de chaque groupe." },
};
