import type { LanguageCode } from "../i18n";

type SummaryText = {
  title: string; all: string; excluding: string; total: string; valid: string; missing: string;
  interacting: string; interactionPercentage: string; minimum: string; maximum: string;
  mean: string; standardDeviation: string; range: string; count: string; percentage: string;
  unknown: string; eyeChanges: string; definitions: string; technicalDetails: string;
  trackingAvailable: string; mostCommonEyeDirection: string; leftRightRange: string;
  upDownRange: string; tiltRange: string;
};
export const computerVisionSummaryTranslations: Record<LanguageCode, SummaryText> = {
  en: { title: "Session Overview", all: "All tracking data", excluding: "Excluding keyboard/mouse activity", total: "Total tracking points", valid: "Valid tracking points", missing: "Tracking unavailable", interacting: "Points during keyboard/mouse activity", interactionPercentage: "Keyboard/mouse activity", minimum: "Minimum", maximum: "Maximum", mean: "Mean", standardDeviation: "Standard deviation", range: "Range", count: "Count", percentage: "Percentage", unknown: "Unknown", eyeChanges: "Eye-direction changes", definitions: "Head statistics use points with all three angles available. Eye percentages include unknown directions. Unavailable or excluded data breaks the direction-change sequence.", technicalDetails: "Show technical details", trackingAvailable: "Face tracking available", mostCommonEyeDirection: "Most common eye direction", leftRightRange: "Left / right movement range", upDownRange: "Up / down movement range", tiltRange: "Head tilt range" },
  es: { title: "Vista general de la sesión", all: "Todos los datos de seguimiento", excluding: "Sin actividad del teclado/ratón", total: "Total de puntos de seguimiento", valid: "Puntos de seguimiento válidos", missing: "Seguimiento no disponible", interacting: "Puntos durante actividad del teclado/ratón", interactionPercentage: "Actividad del teclado/ratón", minimum: "Mínimo", maximum: "Máximo", mean: "Media", standardDeviation: "Desviación estándar", range: "Rango", count: "Cantidad", percentage: "Porcentaje", unknown: "Desconocida", eyeChanges: "Cambios de dirección de los ojos", definitions: "Las estadísticas de cabeza usan puntos con los tres ángulos disponibles. Los porcentajes de los ojos incluyen direcciones desconocidas. Los datos no disponibles o excluidos interrumpen la secuencia de cambios de dirección.", technicalDetails: "Mostrar detalles técnicos", trackingAvailable: "Seguimiento del rostro disponible", mostCommonEyeDirection: "Dirección de ojos más frecuente", leftRightRange: "Rango de movimiento izquierda/derecha", upDownRange: "Rango de movimiento arriba/abajo", tiltRange: "Rango de inclinación de la cabeza" },
  de: { title: "Sitzungsübersicht", all: "Alle Erfassungsdaten", excluding: "Ohne Tastatur-/Mausaktivität", total: "Erfassungspunkte insgesamt", valid: "Gültige Erfassungspunkte", missing: "Erfassung nicht verfügbar", interacting: "Punkte während Tastatur-/Mausaktivität", interactionPercentage: "Tastatur-/Mausaktivität", minimum: "Minimum", maximum: "Maximum", mean: "Mittelwert", standardDeviation: "Standardabweichung", range: "Spannweite", count: "Anzahl", percentage: "Prozent", unknown: "Unbekannt", eyeChanges: "Änderungen der Augenrichtung", definitions: "Kopfstatistiken verwenden Punkte mit drei verfügbaren Winkeln. Augenprozente enthalten unbekannte Richtungen. Fehlende oder ausgeschlossene Daten unterbrechen die Folge der Richtungsänderungen.", technicalDetails: "Technische Details anzeigen", trackingAvailable: "Gesichtserfassung verfügbar", mostCommonEyeDirection: "Häufigste Augenrichtung", leftRightRange: "Bewegungsspanne links/rechts", upDownRange: "Bewegungsspanne oben/unten", tiltRange: "Spanne der Kopfneigung" },
  tr: { title: "Oturuma Genel Bakış", all: "Tüm izleme verileri", excluding: "Klavye/fare etkinliği hariç", total: "Toplam izleme noktası", valid: "Geçerli izleme noktaları", missing: "İzleme kullanılamıyor", interacting: "Klavye/fare etkinliği sırasındaki noktalar", interactionPercentage: "Klavye/fare etkinliği", minimum: "En düşük", maximum: "En yüksek", mean: "Ortalama", standardDeviation: "Standart sapma", range: "Aralık", count: "Sayı", percentage: "Yüzde", unknown: "Bilinmiyor", eyeChanges: "Göz yönü değişimleri", definitions: "Baş istatistikleri, üç açısı da mevcut olan noktaları kullanır. Göz yüzdeleri bilinmeyen yönleri de içerir. Kullanılamayan veya hariç tutulan veriler, yön değişimi dizisini keser.", technicalDetails: "Teknik ayrıntıları göster", trackingAvailable: "Yüz izlemenin kullanılabilirliği", mostCommonEyeDirection: "En sık görülen göz yönü", leftRightRange: "Sağa/sola hareket aralığı", upDownRange: "Yukarı/aşağı hareket aralığı", tiltRange: "Baş eğilme aralığı" },
  pt: { title: "Visão geral da sessão", all: "Todos os dados de rastreamento", excluding: "Sem atividade do teclado/mouse", total: "Total de pontos de rastreamento", valid: "Pontos de rastreamento válidos", missing: "Rastreamento indisponível", interacting: "Pontos durante atividade do teclado/mouse", interactionPercentage: "Atividade do teclado/mouse", minimum: "Mínimo", maximum: "Máximo", mean: "Média", standardDeviation: "Desvio padrão", range: "Amplitude", count: "Contagem", percentage: "Porcentagem", unknown: "Desconhecida", eyeChanges: "Mudanças na direção dos olhos", definitions: "As estatísticas da cabeça usam pontos com os três ângulos disponíveis. As porcentagens dos olhos incluem direções desconhecidas. Dados indisponíveis ou excluídos interrompem a sequência de mudanças de direção.", technicalDetails: "Mostrar detalhes técnicos", trackingAvailable: "Rastreamento do rosto disponível", mostCommonEyeDirection: "Direção dos olhos mais frequente", leftRightRange: "Amplitude do movimento esquerda/direita", upDownRange: "Amplitude do movimento cima/baixo", tiltRange: "Amplitude da inclinação da cabeça" },
  fr: { title: "Vue d’ensemble de la session", all: "Toutes les données de suivi", excluding: "Sans activité du clavier/de la souris", total: "Total des points de suivi", valid: "Points de suivi valides", missing: "Suivi indisponible", interacting: "Points pendant l’activité du clavier/de la souris", interactionPercentage: "Activité du clavier/de la souris", minimum: "Minimum", maximum: "Maximum", mean: "Moyenne", standardDeviation: "Écart-type", range: "Étendue", count: "Nombre", percentage: "Pourcentage", unknown: "Inconnue", eyeChanges: "Changements de direction des yeux", definitions: "Les statistiques de tête utilisent les points avec trois angles disponibles. Les pourcentages des yeux incluent les directions inconnues. Les données indisponibles ou exclues interrompent la séquence des changements de direction.", technicalDetails: "Afficher les détails techniques", trackingAvailable: "Suivi du visage disponible", mostCommonEyeDirection: "Direction des yeux la plus fréquente", leftRightRange: "Amplitude du mouvement gauche/droite", upDownRange: "Amplitude du mouvement haut/bas", tiltRange: "Amplitude de l’inclinaison de la tête" },
};
