import type { LanguageCode } from "../i18n";

type ChartText = { title: string; time: string; angle: string; interaction: string; empty: string; gaps: string; yaw: string; pitch: string; roll: string };
export const headPoseChartTranslations: Record<LanguageCode, ChartText> = {
  en: { title: "Head movement over time", time: "Session time (s)", angle: "Angle (°)", interaction: "Amber areas: keyboard/mouse activity", empty: "No saved head movement data to display.", gaps: "Breaks in the lines show when tracking data was unavailable.", yaw: "Left / right movement", pitch: "Up / down movement", roll: "Head tilt" },
  es: { title: "Movimiento de la cabeza a lo largo del tiempo", time: "Tiempo de sesión (s)", angle: "Ángulo (°)", interaction: "Áreas ámbar: actividad del teclado/ratón", empty: "No hay datos guardados del movimiento de la cabeza para mostrar.", gaps: "Los cortes en las líneas muestran cuándo no había datos de seguimiento.", yaw: "Movimiento izquierda/derecha", pitch: "Movimiento arriba/abajo", roll: "Inclinación de la cabeza" },
  de: { title: "Kopfbewegung im Zeitverlauf", time: "Sitzungszeit (s)", angle: "Winkel (°)", interaction: "Gelbe Bereiche: Tastatur-/Mausaktivität", empty: "Keine gespeicherten Kopfbewegungsdaten vorhanden.", gaps: "Unterbrechungen der Linien zeigen, wann Erfassungsdaten nicht verfügbar waren.", yaw: "Bewegung links/rechts", pitch: "Bewegung oben/unten", roll: "Kopfneigung" },
  tr: { title: "Zamana göre baş hareketi", time: "Oturum süresi (sn)", angle: "Açı (°)", interaction: "Sarı alanlar: klavye/fare etkinliği", empty: "Görüntülenecek kayıtlı baş hareketi verisi yok.", gaps: "Çizgilerdeki boşluklar, izleme verisinin kullanılamadığı zamanları gösterir.", yaw: "Sağa/sola hareket", pitch: "Yukarı/aşağı hareket", roll: "Baş eğilmesi" },
  pt: { title: "Movimento da cabeça ao longo do tempo", time: "Tempo da sessão (s)", angle: "Ângulo (°)", interaction: "Áreas amarelas: atividade do teclado/mouse", empty: "Não há dados salvos do movimento da cabeça para exibir.", gaps: "As interrupções nas linhas mostram quando os dados de rastreamento estavam indisponíveis.", yaw: "Movimento esquerda/direita", pitch: "Movimento cima/baixo", roll: "Inclinação da cabeça" },
  fr: { title: "Mouvement de la tête au fil du temps", time: "Temps de session (s)", angle: "Angle (°)", interaction: "Zones jaunes : activité du clavier/de la souris", empty: "Aucune donnée enregistrée de mouvement de la tête à afficher.", gaps: "Les interruptions des lignes indiquent quand les données de suivi étaient indisponibles.", yaw: "Mouvement gauche/droite", pitch: "Mouvement haut/bas", roll: "Inclinaison de la tête" },
};
