import type { LanguageCode } from "../i18n";

type UsageText = {
  title: string; source: string; month: string; totalCost: string; updated: string;
  model: string; cost: string; requests: string; daily: string; date: string;
  refresh: string; loading: string; error: string; empty: string;
};

export const sonioxUsageTranslations: Record<LanguageCode, UsageText> = {
  en: { title: "Soniox Usage", source: "Official usage for this Soniox project", month: "Current month (UTC)", totalCost: "Total cost this month (USD)", updated: "Last updated", model: "Model", cost: "Cost (USD)", requests: "Requests", daily: "Show daily usage", date: "Date (UTC)", refresh: "Refresh", loading: "Loading Soniox usage…", error: "Soniox usage is currently unavailable. You can still manage speech providers.", empty: "No Soniox usage this month." },
  tr: { title: "Soniox Kullanımı", source: "Bu Soniox projesinin resmi kullanım verileri", month: "Geçerli ay (UTC)", totalCost: "Bu ayın toplam maliyeti (USD)", updated: "Son güncelleme", model: "Model", cost: "Maliyet (USD)", requests: "İstekler", daily: "Günlük kullanımı göster", date: "Tarih (UTC)", refresh: "Yenile", loading: "Soniox kullanımı yükleniyor…", error: "Soniox kullanım verileri şu anda kullanılamıyor. Konuşma sağlayıcılarını yönetmeye devam edebilirsiniz.", empty: "Bu ay Soniox kullanımı yok." },
  es: { title: "Uso de Soniox", source: "Uso oficial de este proyecto de Soniox", month: "Mes actual (UTC)", totalCost: "Costo total de este mes (USD)", updated: "Última actualización", model: "Modelo", cost: "Costo (USD)", requests: "Solicitudes", daily: "Mostrar uso diario", date: "Fecha (UTC)", refresh: "Actualizar", loading: "Cargando uso de Soniox…", error: "El uso de Soniox no está disponible en este momento. Puedes seguir gestionando los proveedores de voz.", empty: "No hay uso de Soniox este mes." },
  de: { title: "Soniox-Nutzung", source: "Offizielle Nutzung dieses Soniox-Projekts", month: "Aktueller Monat (UTC)", totalCost: "Gesamtkosten diesen Monat (USD)", updated: "Zuletzt aktualisiert", model: "Modell", cost: "Kosten (USD)", requests: "Anfragen", daily: "Tägliche Nutzung anzeigen", date: "Datum (UTC)", refresh: "Aktualisieren", loading: "Soniox-Nutzung wird geladen…", error: "Die Soniox-Nutzung ist derzeit nicht verfügbar. Die Sprachanbieter können weiterhin verwaltet werden.", empty: "Keine Soniox-Nutzung in diesem Monat." },
  pt: { title: "Uso do Soniox", source: "Uso oficial deste projeto Soniox", month: "Mês atual (UTC)", totalCost: "Custo total deste mês (USD)", updated: "Última atualização", model: "Modelo", cost: "Custo (USD)", requests: "Solicitações", daily: "Mostrar uso diário", date: "Data (UTC)", refresh: "Atualizar", loading: "Carregando uso do Soniox…", error: "O uso do Soniox está indisponível no momento. Você ainda pode gerenciar os provedores de voz.", empty: "Sem uso do Soniox neste mês." },
  fr: { title: "Utilisation de Soniox", source: "Utilisation officielle de ce projet Soniox", month: "Mois actuel (UTC)", totalCost: "Coût total ce mois-ci (USD)", updated: "Dernière mise à jour", model: "Modèle", cost: "Coût (USD)", requests: "Requêtes", daily: "Afficher l’utilisation quotidienne", date: "Date (UTC)", refresh: "Actualiser", loading: "Chargement de l’utilisation de Soniox…", error: "L’utilisation de Soniox est indisponible pour le moment. Vous pouvez continuer à gérer les fournisseurs vocaux.", empty: "Aucune utilisation de Soniox ce mois-ci." },
};
