import type { LanguageCode } from "../i18n";

export type SpeechProviderText = {
  title: string; description: string; estimatedNotice: string; manageUsers: string; scenarioAnalytics: string;
  tts: string; stt: string; currentProvider: string; mode: string; used: string; configuredLimit: string;
  remaining: string; usage: string; successfulRequests: string; failedRequests: string; cachedRequests: string;
  billingPeriod: string; estimatedReset: string; status: string; automatic: string; azure: string; browser: string;
  normal: string; warning: string; critical: string; quotaReached: string; unavailable: string;
  settings: string; ttsMode: string; sttMode: string; ttsLimit: string; sttLimit: string;
  warningThreshold: string; switchThreshold: string; saveSettings: string; settingsSaved: string;
  loading: string; loadError: string; saveError: string; monthlyHistory: string; noHistory: string;
  eventHistory: string; noEvents: string; date: string; service: string; provider: string;
  requests: string; amountUsed: string; event: string; change: string; reason: string; administrator: string;
  hours: string; minutes: string; seconds: string; characters: string;
  eventNames: Record<string, string>; locale: string;
};

export const speechProviderTranslations: Record<LanguageCode, SpeechProviderText> = {
  en: {
    title: "Speech Provider Management", description: "Monitor estimated Azure usage and control TTS and STT routing.", estimatedNotice: "Estimated Azure usage based on ASSIST-AI requests.", manageUsers: "Manage users", scenarioAnalytics: "Scenario Analytics",
    tts: "Text to Speech (TTS)", stt: "Speech to Text (STT)", currentProvider: "Current provider", mode: "Mode", used: "Used", configuredLimit: "Configured limit", remaining: "Remaining", usage: "Usage", successfulRequests: "Successful requests", failedRequests: "Failed requests", cachedRequests: "Cached requests", billingPeriod: "Billing period", estimatedReset: "Estimated quota reset", status: "Status", automatic: "Automatic", azure: "Azure", browser: "Browser", normal: "Normal", warning: "Warning", critical: "Critical", quotaReached: "Quota reached", unavailable: "Unavailable",
    settings: "Provider settings", ttsMode: "TTS mode", sttMode: "STT mode", ttsLimit: "Azure TTS monthly character limit", sttLimit: "Azure STT monthly seconds limit", warningThreshold: "Warning threshold (%)", switchThreshold: "Automatic switch threshold (%)", saveSettings: "Save settings", settingsSaved: "Speech provider settings saved.", loading: "Loading speech provider data...", loadError: "Speech provider data could not be loaded.", saveError: "Speech provider settings could not be saved.", monthlyHistory: "Monthly usage history", noHistory: "No monthly usage has been recorded yet.", eventHistory: "Provider event history", noEvents: "No provider events have been recorded yet.", date: "Date", service: "Service", provider: "Provider", requests: "Requests", amountUsed: "Amount used", event: "Event", change: "Provider change", reason: "Reason", administrator: "Administrator", hours: "h", minutes: "m", seconds: "s", characters: "characters",
    eventNames: { provider_switched: "Provider switched", automatic_fallback: "Automatic fallback", quota_warning: "Quota warning", quota_reached: "Quota reached", provider_failure: "Provider failure", provider_recovered: "Provider recovered", settings_changed: "Settings changed" }, locale: "en-US",
  },
  es: {
    title: "Gestión de proveedores de voz", description: "Supervisa el uso estimado de Azure y controla el enrutamiento TTS y STT.", estimatedNotice: "Uso estimado de Azure basado en solicitudes de ASSIST-AI.", manageUsers: "Gestionar usuarios", scenarioAnalytics: "Análisis de escenarios",
    tts: "Texto a voz (TTS)", stt: "Voz a texto (STT)", currentProvider: "Proveedor actual", mode: "Modo", used: "Usado", configuredLimit: "Límite configurado", remaining: "Restante", usage: "Uso", successfulRequests: "Solicitudes exitosas", failedRequests: "Solicitudes fallidas", cachedRequests: "Solicitudes en caché", billingPeriod: "Período de facturación", estimatedReset: "Reinicio estimado de cuota", status: "Estado", automatic: "Automático", azure: "Azure", browser: "Navegador", normal: "Normal", warning: "Advertencia", critical: "Crítico", quotaReached: "Cuota alcanzada", unavailable: "No disponible",
    settings: "Configuración de proveedores", ttsMode: "Modo TTS", sttMode: "Modo STT", ttsLimit: "Límite mensual de caracteres TTS de Azure", sttLimit: "Límite mensual de segundos STT de Azure", warningThreshold: "Umbral de advertencia (%)", switchThreshold: "Umbral de cambio automático (%)", saveSettings: "Guardar configuración", settingsSaved: "Configuración de proveedores guardada.", loading: "Cargando datos de voz...", loadError: "No se pudieron cargar los datos de voz.", saveError: "No se pudo guardar la configuración.", monthlyHistory: "Historial mensual de uso", noHistory: "Todavía no hay uso mensual registrado.", eventHistory: "Historial de eventos", noEvents: "Todavía no hay eventos registrados.", date: "Fecha", service: "Servicio", provider: "Proveedor", requests: "Solicitudes", amountUsed: "Cantidad usada", event: "Evento", change: "Cambio de proveedor", reason: "Motivo", administrator: "Administrador", hours: "h", minutes: "min", seconds: "s", characters: "caracteres",
    eventNames: { provider_switched: "Proveedor cambiado", automatic_fallback: "Cambio automático", quota_warning: "Advertencia de cuota", quota_reached: "Cuota alcanzada", provider_failure: "Fallo del proveedor", provider_recovered: "Proveedor recuperado", settings_changed: "Configuración modificada" }, locale: "es-ES",
  },
  de: {
    title: "Sprachanbieter-Verwaltung", description: "Überwache die geschätzte Azure-Nutzung und steuere das TTS- und STT-Routing.", estimatedNotice: "Geschätzte Azure-Nutzung basierend auf ASSIST-AI-Anfragen.", manageUsers: "Benutzer verwalten", scenarioAnalytics: "Szenarioanalysen",
    tts: "Text zu Sprache (TTS)", stt: "Sprache zu Text (STT)", currentProvider: "Aktueller Anbieter", mode: "Modus", used: "Verwendet", configuredLimit: "Konfiguriertes Limit", remaining: "Verbleibend", usage: "Nutzung", successfulRequests: "Erfolgreiche Anfragen", failedRequests: "Fehlgeschlagene Anfragen", cachedRequests: "Cache-Anfragen", billingPeriod: "Abrechnungszeitraum", estimatedReset: "Geschätzte Rücksetzung", status: "Status", automatic: "Automatisch", azure: "Azure", browser: "Browser", normal: "Normal", warning: "Warnung", critical: "Kritisch", quotaReached: "Kontingent erreicht", unavailable: "Nicht verfügbar",
    settings: "Anbietereinstellungen", ttsMode: "TTS-Modus", sttMode: "STT-Modus", ttsLimit: "Monatliches Azure-TTS-Zeichenlimit", sttLimit: "Monatliches Azure-STT-Sekundenlimit", warningThreshold: "Warnschwelle (%)", switchThreshold: "Automatische Wechselschwelle (%)", saveSettings: "Einstellungen speichern", settingsSaved: "Sprachanbieter-Einstellungen gespeichert.", loading: "Sprachanbieter-Daten werden geladen...", loadError: "Sprachanbieter-Daten konnten nicht geladen werden.", saveError: "Einstellungen konnten nicht gespeichert werden.", monthlyHistory: "Monatlicher Nutzungsverlauf", noHistory: "Noch keine monatliche Nutzung erfasst.", eventHistory: "Anbieter-Ereignisverlauf", noEvents: "Noch keine Anbieterereignisse erfasst.", date: "Datum", service: "Dienst", provider: "Anbieter", requests: "Anfragen", amountUsed: "Verwendete Menge", event: "Ereignis", change: "Anbieterwechsel", reason: "Grund", administrator: "Administrator", hours: "Std.", minutes: "Min.", seconds: "Sek.", characters: "Zeichen",
    eventNames: { provider_switched: "Anbieter gewechselt", automatic_fallback: "Automatischer Rückfall", quota_warning: "Kontingentwarnung", quota_reached: "Kontingent erreicht", provider_failure: "Anbieterfehler", provider_recovered: "Anbieter wiederhergestellt", settings_changed: "Einstellungen geändert" }, locale: "de-DE",
  },
  tr: {
    title: "Konuşma Sağlayıcısı Yönetimi", description: "Tahmini Azure kullanımını izleyin ve TTS ile STT yönlendirmesini yönetin.", estimatedNotice: "ASSIST-AI isteklerine göre tahmini Azure kullanımı.", manageUsers: "Kullanıcıları yönet", scenarioAnalytics: "Senaryo Analizleri",
    tts: "Metinden Sese (TTS)", stt: "Sesten Metne (STT)", currentProvider: "Geçerli sağlayıcı", mode: "Mod", used: "Kullanılan", configuredLimit: "Yapılandırılmış sınır", remaining: "Kalan", usage: "Kullanım", successfulRequests: "Başarılı istekler", failedRequests: "Başarısız istekler", cachedRequests: "Önbellek istekleri", billingPeriod: "Fatura dönemi", estimatedReset: "Tahmini kota yenilenmesi", status: "Durum", automatic: "Otomatik", azure: "Azure", browser: "Tarayıcı", normal: "Normal", warning: "Uyarı", critical: "Kritik", quotaReached: "Kotaya ulaşıldı", unavailable: "Kullanılamıyor",
    settings: "Sağlayıcı ayarları", ttsMode: "TTS modu", sttMode: "STT modu", ttsLimit: "Azure TTS aylık karakter sınırı", sttLimit: "Azure STT aylık saniye sınırı", warningThreshold: "Uyarı eşiği (%)", switchThreshold: "Otomatik geçiş eşiği (%)", saveSettings: "Ayarları kaydet", settingsSaved: "Konuşma sağlayıcısı ayarları kaydedildi.", loading: "Konuşma sağlayıcısı verileri yükleniyor...", loadError: "Konuşma sağlayıcısı verileri yüklenemedi.", saveError: "Sağlayıcı ayarları kaydedilemedi.", monthlyHistory: "Aylık kullanım geçmişi", noHistory: "Henüz aylık kullanım kaydedilmedi.", eventHistory: "Sağlayıcı olay geçmişi", noEvents: "Henüz sağlayıcı olayı kaydedilmedi.", date: "Tarih", service: "Hizmet", provider: "Sağlayıcı", requests: "İstekler", amountUsed: "Kullanılan miktar", event: "Olay", change: "Sağlayıcı değişikliği", reason: "Neden", administrator: "Yönetici", hours: "sa", minutes: "dk", seconds: "sn", characters: "karakter",
    eventNames: { provider_switched: "Sağlayıcı değiştirildi", automatic_fallback: "Otomatik yedek sağlayıcı", quota_warning: "Kota uyarısı", quota_reached: "Kotaya ulaşıldı", provider_failure: "Sağlayıcı hatası", provider_recovered: "Sağlayıcı düzeldi", settings_changed: "Ayarlar değiştirildi" }, locale: "tr-TR",
  },
  pt: {
    title: "Gestão de Provedores de Voz", description: "Monitore o uso estimado do Azure e controle o roteamento TTS e STT.", estimatedNotice: "Uso estimado do Azure com base nas solicitações do ASSIST-AI.", manageUsers: "Gerenciar usuários", scenarioAnalytics: "Análises de Cenários",
    tts: "Texto para Voz (TTS)", stt: "Voz para Texto (STT)", currentProvider: "Provedor atual", mode: "Modo", used: "Usado", configuredLimit: "Limite configurado", remaining: "Restante", usage: "Uso", successfulRequests: "Solicitações bem-sucedidas", failedRequests: "Solicitações com falha", cachedRequests: "Solicitações em cache", billingPeriod: "Período de faturamento", estimatedReset: "Reinício estimado da cota", status: "Status", automatic: "Automático", azure: "Azure", browser: "Navegador", normal: "Normal", warning: "Aviso", critical: "Crítico", quotaReached: "Cota atingida", unavailable: "Indisponível",
    settings: "Configurações dos provedores", ttsMode: "Modo TTS", sttMode: "Modo STT", ttsLimit: "Limite mensal de caracteres TTS do Azure", sttLimit: "Limite mensal de segundos STT do Azure", warningThreshold: "Limite de aviso (%)", switchThreshold: "Limite de troca automática (%)", saveSettings: "Salvar configurações", settingsSaved: "Configurações dos provedores salvas.", loading: "Carregando dados dos provedores...", loadError: "Não foi possível carregar os dados dos provedores.", saveError: "Não foi possível salvar as configurações.", monthlyHistory: "Histórico mensal de uso", noHistory: "Nenhum uso mensal foi registrado.", eventHistory: "Histórico de eventos", noEvents: "Nenhum evento foi registrado.", date: "Data", service: "Serviço", provider: "Provedor", requests: "Solicitações", amountUsed: "Quantidade usada", event: "Evento", change: "Mudança de provedor", reason: "Motivo", administrator: "Administrador", hours: "h", minutes: "min", seconds: "s", characters: "caracteres",
    eventNames: { provider_switched: "Provedor alterado", automatic_fallback: "Alternativa automática", quota_warning: "Aviso de cota", quota_reached: "Cota atingida", provider_failure: "Falha do provedor", provider_recovered: "Provedor recuperado", settings_changed: "Configurações alteradas" }, locale: "pt-PT",
  },
  fr: {
    title: "Gestion des fournisseurs vocaux", description: "Surveillez l’utilisation estimée d’Azure et contrôlez le routage TTS et STT.", estimatedNotice: "Utilisation Azure estimée à partir des requêtes ASSIST-AI.", manageUsers: "Gérer les utilisateurs", scenarioAnalytics: "Analyse des scénarios",
    tts: "Texte vers parole (TTS)", stt: "Parole vers texte (STT)", currentProvider: "Fournisseur actuel", mode: "Mode", used: "Utilisé", configuredLimit: "Limite configurée", remaining: "Restant", usage: "Utilisation", successfulRequests: "Requêtes réussies", failedRequests: "Requêtes échouées", cachedRequests: "Requêtes en cache", billingPeriod: "Période de facturation", estimatedReset: "Réinitialisation estimée", status: "Statut", automatic: "Automatique", azure: "Azure", browser: "Navigateur", normal: "Normal", warning: "Avertissement", critical: "Critique", quotaReached: "Quota atteint", unavailable: "Indisponible",
    settings: "Paramètres des fournisseurs", ttsMode: "Mode TTS", sttMode: "Mode STT", ttsLimit: "Limite mensuelle de caractères TTS Azure", sttLimit: "Limite mensuelle de secondes STT Azure", warningThreshold: "Seuil d’avertissement (%)", switchThreshold: "Seuil de basculement automatique (%)", saveSettings: "Enregistrer", settingsSaved: "Paramètres des fournisseurs enregistrés.", loading: "Chargement des données vocales...", loadError: "Impossible de charger les données vocales.", saveError: "Impossible d’enregistrer les paramètres.", monthlyHistory: "Historique mensuel d’utilisation", noHistory: "Aucune utilisation mensuelle enregistrée.", eventHistory: "Historique des événements", noEvents: "Aucun événement de fournisseur enregistré.", date: "Date", service: "Service", provider: "Fournisseur", requests: "Requêtes", amountUsed: "Quantité utilisée", event: "Événement", change: "Changement de fournisseur", reason: "Raison", administrator: "Administrateur", hours: "h", minutes: "min", seconds: "s", characters: "caractères",
    eventNames: { provider_switched: "Fournisseur changé", automatic_fallback: "Basculement automatique", quota_warning: "Avertissement de quota", quota_reached: "Quota atteint", provider_failure: "Échec du fournisseur", provider_recovered: "Fournisseur rétabli", settings_changed: "Paramètres modifiés" }, locale: "fr-FR",
  },
};
