import type { LanguageCode } from "../i18n";

export type SpeechUsageText = {
  locale: string; eyebrow: string; title: string; intro: string; loadError: string; submitted: string; requestFailed: string;
  ttsTitle: string; sttTitle: string; currentPeriod: string; nextReset: string; status: string; notifications: string;
  requestTitle: string; service: string; both: string; ttsCharacters: string; sttMinutes: string; reason: string; submit: string;
  history: string; admin: string; empty: string; used: string; remaining: string; total: string; permanent: string;
  temporary: string; expires: string; atReset: string; weekly: string; normal: string; warning: string; critical: string;
  disabled: string; pending: string; approved: string; rejected: string;
};

export const speechUsageTranslations: Record<LanguageCode, SpeechUsageText> = {
  en: { locale: "en-US", eyebrow: "Personal allowance", title: "My Speech Usage", intro: "Review your current allowance and request additional access when needed.", loadError: "Speech usage could not be loaded.", submitted: "Your request was submitted.", requestFailed: "Request failed.", ttsTitle: "TTS characters", sttTitle: "STT speech time", currentPeriod: "Current period", nextReset: "Next reset", status: "Status", notifications: "Quota notifications", requestTitle: "Request additional quota", service: "Service", both: "TTS and STT", ttsCharacters: "TTS characters", sttMinutes: "STT minutes", reason: "Reason", submit: "Submit request", history: "Request history", admin: "Admin", empty: "No requests yet.", used: "Used", remaining: "Remaining", total: "Total", permanent: "Permanent", temporary: "Temporary", expires: "expires", atReset: "at reset", weekly: "Weekly", normal: "Normal", warning: "Warning", critical: "Critical", disabled: "Disabled", pending: "Pending", approved: "Approved", rejected: "Rejected" },
  es: { locale: "es-ES", eyebrow: "Asignación personal", title: "Mi uso de voz", intro: "Consulta tu asignación actual y solicita acceso adicional cuando lo necesites.", loadError: "No se pudo cargar el uso de voz.", submitted: "Tu solicitud fue enviada.", requestFailed: "La solicitud falló.", ttsTitle: "Caracteres TTS", sttTitle: "Tiempo de voz STT", currentPeriod: "Período actual", nextReset: "Próximo reinicio", status: "Estado", notifications: "Notificaciones de cuota", requestTitle: "Solicitar cuota adicional", service: "Servicio", both: "TTS y STT", ttsCharacters: "Caracteres TTS", sttMinutes: "Minutos STT", reason: "Motivo", submit: "Enviar solicitud", history: "Historial de solicitudes", admin: "Administrador", empty: "Aún no hay solicitudes.", used: "Usado", remaining: "Restante", total: "Total", permanent: "Permanente", temporary: "Temporal", expires: "vence", atReset: "al reiniciar", weekly: "Semanal", normal: "Normal", warning: "Advertencia", critical: "Crítico", disabled: "Desactivado", pending: "Pendiente", approved: "Aprobado", rejected: "Rechazado" },
  de: { locale: "de-DE", eyebrow: "Persönliches Kontingent", title: "Meine Sprachnutzung", intro: "Prüfen Sie Ihr aktuelles Kontingent und beantragen Sie bei Bedarf zusätzlichen Zugang.", loadError: "Die Sprachnutzung konnte nicht geladen werden.", submitted: "Ihre Anfrage wurde gesendet.", requestFailed: "Die Anfrage ist fehlgeschlagen.", ttsTitle: "TTS-Zeichen", sttTitle: "STT-Sprechzeit", currentPeriod: "Aktueller Zeitraum", nextReset: "Nächste Rücksetzung", status: "Status", notifications: "Kontingentbenachrichtigungen", requestTitle: "Zusätzliches Kontingent beantragen", service: "Dienst", both: "TTS und STT", ttsCharacters: "TTS-Zeichen", sttMinutes: "STT-Minuten", reason: "Begründung", submit: "Anfrage senden", history: "Anfrageverlauf", admin: "Administration", empty: "Noch keine Anfragen.", used: "Verwendet", remaining: "Verbleibend", total: "Gesamt", permanent: "Dauerhaft", temporary: "Temporär", expires: "läuft ab", atReset: "bei Rücksetzung", weekly: "Wöchentlich", normal: "Normal", warning: "Warnung", critical: "Kritisch", disabled: "Deaktiviert", pending: "Ausstehend", approved: "Genehmigt", rejected: "Abgelehnt" },
  tr: { locale: "tr-TR", eyebrow: "Kişisel kullanım hakkı", title: "Konuşma Kullanımım", intro: "Mevcut kullanım hakkınızı inceleyin ve gerektiğinde ek kota talep edin.", loadError: "Konuşma kullanımı yüklenemedi.", submitted: "Talebiniz gönderildi.", requestFailed: "Talep gönderilemedi.", ttsTitle: "TTS karakterleri", sttTitle: "STT konuşma süresi", currentPeriod: "Geçerli dönem", nextReset: "Sonraki yenileme", status: "Durum", notifications: "Kota bildirimleri", requestTitle: "Ek kota talep et", service: "Hizmet", both: "TTS ve STT", ttsCharacters: "TTS karakterleri", sttMinutes: "STT dakikası", reason: "Gerekçe", submit: "Talep gönder", history: "Talep geçmişi", admin: "Yönetici", empty: "Henüz talep yok.", used: "Kullanılan", remaining: "Kalan", total: "Toplam", permanent: "Kalıcı", temporary: "Geçici", expires: "sona erer", atReset: "yenileme tarihinde", weekly: "Haftalık", normal: "Normal", warning: "Uyarı", critical: "Kritik", disabled: "Devre dışı", pending: "Bekliyor", approved: "Onaylandı", rejected: "Reddedildi" },
  pt: { locale: "pt-PT", eyebrow: "Limite pessoal", title: "A minha utilização de voz", intro: "Consulte o seu limite atual e solicite acesso adicional quando necessário.", loadError: "Não foi possível carregar a utilização de voz.", submitted: "O seu pedido foi enviado.", requestFailed: "O pedido falhou.", ttsTitle: "Caracteres TTS", sttTitle: "Tempo de fala STT", currentPeriod: "Período atual", nextReset: "Próxima reposição", status: "Estado", notifications: "Notificações de quota", requestTitle: "Pedir quota adicional", service: "Serviço", both: "TTS e STT", ttsCharacters: "Caracteres TTS", sttMinutes: "Minutos STT", reason: "Motivo", submit: "Enviar pedido", history: "Histórico de pedidos", admin: "Administrador", empty: "Ainda não existem pedidos.", used: "Utilizado", remaining: "Restante", total: "Total", permanent: "Permanente", temporary: "Temporário", expires: "expira", atReset: "na reposição", weekly: "Semanal", normal: "Normal", warning: "Aviso", critical: "Crítico", disabled: "Desativado", pending: "Pendente", approved: "Aprovado", rejected: "Rejeitado" },
  fr: { locale: "fr-FR", eyebrow: "Quota personnelle", title: "Mon utilisation vocale", intro: "Consultez votre quota actuel et demandez un accès supplémentaire si nécessaire.", loadError: "L’utilisation vocale n’a pas pu être chargée.", submitted: "Votre demande a été envoyée.", requestFailed: "La demande a échoué.", ttsTitle: "Caractères TTS", sttTitle: "Temps de parole STT", currentPeriod: "Période actuelle", nextReset: "Prochaine réinitialisation", status: "Statut", notifications: "Notifications de quota", requestTitle: "Demander un quota supplémentaire", service: "Service", both: "TTS et STT", ttsCharacters: "Caractères TTS", sttMinutes: "Minutes STT", reason: "Motif", submit: "Envoyer la demande", history: "Historique des demandes", admin: "Administrateur", empty: "Aucune demande pour le moment.", used: "Utilisé", remaining: "Restant", total: "Total", permanent: "Permanent", temporary: "Temporaire", expires: "expire", atReset: "à la réinitialisation", weekly: "Hebdomadaire", normal: "Normal", warning: "Avertissement", critical: "Critique", disabled: "Désactivé", pending: "En attente", approved: "Approuvé", rejected: "Refusé" },
};
